name: Node.js CI

on:
  push:
    branches: [ "main", "feature/SCRUM-11-user-account-creation" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install deps
      run: npm install
    - name: Build app
      run: npm run build
